version: "3.5"

services:
  app:
    image: golang:1.18.3-alpine3.16
    working_dir: /app
    container_name: go-app
    volumes:
      - .:/app
    command: go run src/main.go
    ports:
      - 8080:8080
  mysql:
    image: percona:8.0.28-20
    container_name: go-mysql
    ports:
      - 52001:3306
    restart: on-failure 
    volumes:
      - ./migrations:/migrations
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root